### ISSUE TITLE
.gitignore missing entries.

### ISSUE THREAD

**Issue by Sslaxx** [ToadsworthLP/Tortellini#1]
The current `.gitignore` is currently pretty bare-bones and not really meant for a project using Godot (for example, the `.import/` directory is still being pulled in commits, when it doesn't need to be - *don't* confuse these with *.import files that *do*, however!).

https://github.com/Sslaxx/Godot_Sonic_Engine/blob/marmito_physics_rewrite/.gitignore might be worth looking at using?

**Comment by Sslaxx** [comment]
If you're using the Mono build of Godot, you may want to consider adding entries for `.vs/` and `.mono/` directories as well, and possibly other Mono-related temporary files.

**Comment by ToadsworthLP** [comment]
Thank you for reminding me about that! I didn't update the gitignore file since the early Unity days of this project, but that's an easy fix. Will be fixed later today!

**Comment by ToadsworthLP** [comment]
Fixed in #676ab64
